import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <Navbar />
      <section className="pt-32 pb-24 px-4 sm:px-6 lg:px-8 max-w-3xl mx-auto">
        <h1 className="text-4xl sm:text-5xl font-bold font-heading text-charcoal mb-8">Terms of Service</h1>

        <div className="prose prose-lg max-w-none text-charcoal-light space-y-6">
          <p className="text-sm text-charcoal-light/60">Last updated: May 2026</p>

          <h2 className="text-xl font-bold font-heading text-charcoal mt-8">1. Acceptance of Terms</h2>
          <p>
            By using ToastGen ("the Service"), you agree to these Terms of Service. If you do not agree, please do not use the Service.
          </p>

          <h2 className="text-xl font-bold font-heading text-charcoal mt-8">2. Description of Service</h2>
          <p>
            ToastGen is an AI-powered wedding speech generation tool. You provide details about the couple, your relationship, and your stories; we generate a personalized wedding speech draft for you to review, edit, and deliver.
          </p>

          <h2 className="text-xl font-bold font-heading text-charcoal mt-8">3. User Responsibilities</h2>
          <p>
            You are responsible for the content you submit and the speech you deliver. While we strive to generate appropriate and high-quality content, you should review and edit the generated speech before delivery. Do not submit content that is illegal, offensive, or infringes on others' rights.
          </p>

          <h2 className="text-xl font-bold font-heading text-charcoal mt-8">4. AI-Generated Content</h2>
          <p>
            Speeches are generated by artificial intelligence based on your inputs. Results may vary. We do not guarantee that generated content will be free of errors, entirely original, or perfectly suited to your needs. You assume responsibility for the final speech you deliver.
          </p>

          <h2 className="text-xl font-bold font-heading text-charcoal mt-8">5. Payments and Refunds</h2>
          <p>
            Paid plans grant you a specific number of speech generations as described at the time of purchase. Credits do not expire. You may request a full refund within 14 days of purchase, provided that no speech generations from the purchased pack have been used. Once any speech has been generated using your purchased credits, the purchase is considered consumed and is no longer eligible for a refund. To request a refund, contact us at hello@toastgen.org. Refunds will be processed within 5-10 business days to the original payment method.
          </p>

          <h2 className="text-xl font-bold font-heading text-charcoal mt-8">6. Intellectual Property</h2>
          <p>
            The speech content generated for you belongs to you. You may use, modify, and deliver it as you see fit. The ToastGen platform, branding, and underlying technology remain our intellectual property.
          </p>

          <h2 className="text-xl font-bold font-heading text-charcoal mt-8">7. Limitation of Liability</h2>
          <p>
            ToastGen is provided "as is." We are not liable for any damages arising from your use of the Service, including but not limited to speech delivery outcomes, event disruptions, or emotional distress.
          </p>

          <h2 className="text-xl font-bold font-heading text-charcoal mt-8">8. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the new Terms.
          </p>

          <h2 className="text-xl font-bold font-heading text-charcoal mt-8">9. Contact</h2>
          <p>
            For questions about these Terms, please visit our <a href="/contact" className="text-champagne hover:underline">Contact page</a>.
          </p>
        </div>
      </section>
      <Footer />
    </div>
  );
}
